# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\Main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc

class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(953, 654)
        MainMenu.setStyleSheet("""
            QDialog {
                background-image: url(":/resources/Milionerzy_tlo.jpg");
                background-repeat: no-repeat;
                background-position: center;
            }

            QPushButton {
                background-color: rgba(0, 0, 0, 180);
                color: white;
                border: 2px solid white;
                border-radius: 10px;
                padding: 8px;
                font-size: 12px;
            }

            QPushButton:hover {
                background-color: rgba(50, 50, 50, 200);
            }

            QPushButton:pressed {
                background-color: rgba(80, 80, 80, 220);
            }
        """)

        self.verticalLayoutWidget = QtWidgets.QWidget(MainMenu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(450, 10, 451, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Nowa_gra = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Nowa_gra.setObjectName("Nowa_gra")
        self.verticalLayout.addWidget(self.Nowa_gra)
        self.Dodaj_pytania = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Dodaj_pytania.setObjectName("Dodaj_pytania")
        self.verticalLayout.addWidget(self.Dodaj_pytania)
        self.Tabela_wynikow = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Tabela_wynikow.setObjectName("Tabela_wynikow")
        self.verticalLayout.addWidget(self.Tabela_wynikow)
        self.Wyjdz = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Wyjdz.setObjectName("Wyjdz")
        self.verticalLayout.addWidget(self.Wyjdz)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Dialog"))
        self.Nowa_gra.setText(_translate("MainMenu", "Nowa Gra"))
        self.Dodaj_pytania.setText(_translate("MainMenu", "Dodaj pytania"))
        self.Tabela_wynikow.setText(_translate("MainMenu", "Tabela wyników"))
        self.Wyjdz.setText(_translate("MainMenu", "Wyjdź"))

