# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 200, 331, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Odpowiedzi = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Odpowiedzi.setContentsMargins(0, 0, 0, 0)
        self.Odpowiedzi.setObjectName("Odpowiedzi")
        self.Odpowiedz1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Odpowiedz1.setObjectName("Odpowiedz1")
        self.Odpowiedzi.addWidget(self.Odpowiedz1, 0, 0, 1, 1)
        self.Odpowiedz2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Odpowiedz2.setObjectName("Odpowiedz2")
        self.Odpowiedzi.addWidget(self.Odpowiedz2, 1, 0, 1, 1)
        self.Odpowiedz3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Odpowiedz3.setObjectName("Odpowiedz3")
        self.Odpowiedzi.addWidget(self.Odpowiedz3, 2, 0, 1, 1)
        self.Odpowiedz4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Odpowiedz4.setObjectName("Odpowiedz4")
        self.Odpowiedzi.addWidget(self.Odpowiedz4, 3, 0, 1, 1)
        self.Pytanie = QtWidgets.QLabel(self.centralwidget)
        self.Pytanie.setEnabled(False)
        self.Pytanie.setGeometry(QtCore.QRect(100, 180, 201, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pytanie.sizePolicy().hasHeightForWidth())
        self.Pytanie.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Pytanie.setFont(font)
        self.Pytanie.setAutoFillBackground(False)
        self.Pytanie.setFrameShape(QtWidgets.QFrame.Panel)
        self.Pytanie.setScaledContents(False)
        self.Pytanie.setWordWrap(True)
        self.Pytanie.setObjectName("Pytanie")
        self.Nr_pytania = QtWidgets.QLCDNumber(self.centralwidget)
        self.Nr_pytania.setEnabled(False)
        self.Nr_pytania.setGeometry(QtCore.QRect(0, 170, 64, 23))
        self.Nr_pytania.setObjectName("Nr_pytania")
        self.Suma = QtWidgets.QLCDNumber(self.centralwidget)
        self.Suma.setGeometry(QtCore.QRect(330, 260, 81, 51))
        self.Suma.setObjectName("Suma")
        self.Ile_za_pytanie = QtWidgets.QLCDNumber(self.centralwidget)
        self.Ile_za_pytanie.setGeometry(QtCore.QRect(0, 140, 64, 23))
        self.Ile_za_pytanie.setObjectName("Ile_za_pytanie")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Odpowiedz1.setText(_translate("MainWindow", "Odp1"))
        self.Odpowiedz2.setText(_translate("MainWindow", "Odp2"))
        self.Odpowiedz3.setText(_translate("MainWindow", "Odp3"))
        self.Odpowiedz4.setText(_translate("MainWindow", "Odp4"))
        self.Pytanie.setText(_translate("MainWindow", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
